WARNING = "Warning"
ERROR = "Error"
OK = "Ok"
SUCCESS = "Success"
ANSWER = "Answer"

DATA = "Data"

LOGIN = "Login"
PASSWORD = "Password"
ID_USER = "id_user"
NAME = "Name"
SURNAME = "Surname"
EMAIL = "Email"
SEX = "Sex"
CITY = "City"
EDUCATION = "Educational"
LOGO_NAME = "Logo_name"
LOGO = "Logo"
UUID = "UUID"
